@startuml
'https://plantuml.com/class-diagram


package application {
    package service {
'        class BlogEntryCollectorService

        package converter {
            class BlogsToDocsConverter
            class DocsToBlogsConverter
        }
    }
}

application.service.converter.BlogsToDocsConverter ..> domain.blogs.BlogEntry
application.service.converter.BlogsToDocsConverter ..> domain.docs.DocEntry
application.service.converter.DocsToBlogsConverter ..> domain.blogs.BlogEntry
application.service.converter.DocsToBlogsConverter ..> domain.docs.DocEntry

'application.service.BlogEntryCollectorService ..> domain.converter
'application.service.BlogEntryCollectorService ...> domain.store
'application.service.BlogEntryCollectorService ...> domain.blogs
'application.service.BlogEntryCollectorService ...> domain.docs

package domain {
    package blogs {
        class BlogEntry
    }
    package docs {
        class DocEntry
    }
    package entries {
        interface IEntry
        class EntryTree
        interface IStoredEntryAccessor
        EntryTreeRestorer .> EntryTree
        EntryTree .> IEntry
    }
    blogs.BlogEntry ..|> entries.IEntry
    docs.DocEntry ..|> entries.IEntry
}

domain.entries.EntryTreeRestorer ..> domain.entries.IStoredEntryAccessor
domain.entries.IEntry <.. infrastructure.store.StoredEntryAccessor
domain.entries.IStoredEntryAccessor <|.. infrastructure.store.StoredEntryAccessor

package infrastructure {
    package store {
        class StoredEntryAccessor
    }
}

@enduml